# Generated by Django 6.0.3 on 2026-03-23 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('tax_code', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('legal_representative', models.CharField(blank=True, max_length=255)),
                ('industry', models.TextField(blank=True)),
                ('main_customer', models.TextField(blank=True)),
                ('branches_in_vn', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=500)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('scale', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.company')),
            ],
        ),
    ]
