# Generated by Django 6.0.3 on 2026-03-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, help_text='Ghi chú về công ty'),
        ),
    ]
