# Generated by Django 6.0.3 on 2026-03-25 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('product_seats', models.IntegerField()),
                ('license_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('partner', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_records', to='core.company')),
            ],
        ),
    ]
