# Generated by Django 6.0.3 on 2026-03-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_licenserecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=505),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.TextField(blank=True),
        ),
    ]
