# Generated by Django 6.0.3 on 2026-03-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='export_info',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='InfringementOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_infringement_computers', models.IntegerField()),
                ('infringement_time', models.CharField(max_length=255)),
                ('event_to_quote', models.CharField(max_length=255)),
                ('infringement_softwares', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('infringement_address', models.CharField(blank=True, max_length=255)),
                ('other_softwares', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infringement_overviews', to='core.company')),
            ],
        ),
    ]
