# Generated by Django 6.0.3 on 2026-03-27 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_event_to_quote_and_alter_infringement_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedCSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='imports/csv/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InfringementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(blank=True)),
                ('product', models.TextField(blank=True)),
                ('version', models.TextField(blank=True)),
                ('release', models.TextField(blank=True)),
                ('feature_used', models.TextField(blank=True)),
                ('active_mac', models.TextField(blank=True)),
                ('mac2', models.TextField(blank=True)),
                ('mac3', models.TextField(blank=True)),
                ('mac4', models.TextField(blank=True)),
                ('system_model', models.TextField(blank=True)),
                ('wifi_latitude', models.TextField(blank=True)),
                ('wifi_longityde', models.TextField(blank=True)),
                ('public_ip_address', models.TextField(blank=True)),
                ('gateway_mac_address', models.TextField(blank=True)),
                ('active_wifi_access_point', models.TextField(blank=True)),
                ('license_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infringement_details', to='core.importedcsvfile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
