# Generated by Django 6.0.3 on 2026-03-27 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_importedcsvfile_infringementdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedcsvfile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_csv_files', to='core.company'),
        ),
        migrations.AddField(
            model_name='infringementdetail',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infringement_detail', to='core.company'),
        ),
        migrations.AlterField(
            model_name='infringementdetail',
            name='imported_csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infringement_details', to='core.importedcsvfile'),
        ),
        migrations.RenameField(
            model_name='infringementdetail',
            old_name='wifi_longityde',
            new_name='wifi_longitude',
        ),
        migrations.AddField(
            model_name='infringementdetail',
            name='ip_latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='infringementdetail',
            name='ip_longitude',
            field=models.TextField(blank=True),
        ),
    ]
