# Generated by Django 6.0.3 on 2026-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_coordinate_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedcsvfile',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='imports/csv/'),
        ),
    ]
